### ISSUE TITLE
Uglify overhead

### ISSUE THREAD

**Issue by unindented** [bazilio91/ejs-compiled-loader#1]
Why add the overhead of prettifying the generated template? https://github.com/bazilio91/ejs-compiled-loader/blob/4e03097ba49ff684394776e2a14e69fe54cdd914/index.js#L11-L13

We want the loader to be as fast as possible, right?

**Comment by bazilio91** [comment]
fixed in https://github.com/bazilio91/ejs-compiled-loader/commit/6efcc2eea332af7626e0097c03254e8801de7379

**Comment by unindented** [comment]
:+1:
