### ISSUE TITLE
Add some additional docs for webpack 2 usage.

### ISSUE THREAD

**Issue by scriptjs** [bazilio91/ejs-compiled-loader#13]
Hello, you may add the following note for webpack 2 usage. Please add my github name as a contributor to the package if you decide to include this in your docs.

---

Note that ‘with’ that is deprecated in es6. For webpack 2 usage, you must pass an option in your query strict=true or _with=false that will disable `with` in the ejs package.

Examples: 
strict=true

```
import tmpl1 from '!!../?strict=true!./template.ejs';
import tmpl2 from '!!../?delimiter=?&strict=true!./template2.ejs';
import tmpl3 from '!!../?strict=true!./subdir/parent.ejs';
```

_with=false

```
import tmpl1 from '!!../?_with=false!./template.ejs';
import tmpl2 from '!!../?delimiter=?&_with=false!./template2.ejs';
import tmpl3 from '!!../?_with=false!./subdir/parent.ejs';
```

Template examples:

You will need to refer to your vars from the locals object when `with` has been disabled as illustrated below:

```
Hello, <%=locals.noun%>!
```

```
<? for(var key in locals.hobbies) { var hobby = locals.hobbies[key]; -?>
  I like {{=hobby}}.
<? } ?>
```

```
child: <%= locals.foo %>
```

**Comment by jolyonruss** [comment]
@scriptjs can you elaborate on this syntax `import tmpl1 from '!!../?strict=true!./template.ejs';`?

I'm trying to get ejs-compiled-loader working in a project and am having to resort to a require to get my template loaded like this `var template = require('ejs-compiled!./../../../templates_new/site/site_header.ejs');`

If I use an import like your example Webpack fails with a Cannot resolve directory '..' error.

Also, when I render or log the template I get a load of module.exports = function anonymous stuff being returned, I'd expect to just get the HTML from the template

**Comment by scriptjs** [comment]
@jolyonruss 

Import is es6 syntax that you do not appear to be using. If not using es6 syntax, why complicate matters and continue to use webpack 1.x.

Whether you work with webpack 1 or 2, you should be working with a loader in your config file making it unnecessary to spell the loader in your url.

Second, the above are examples and are not meant to be taken literally. The examples coincide with the assertions made in config within the test folder for this project. You will need to adjust the path to you own template (which is why is complains it cannot find the path in your code).

With the loader in your config, your url might look more like:

```
!!./../../../?strict=true!./templates_new/site/site_header.ejs
```

Not sure how your project is structured but that is a very deep hierarchy in your project that seems quite strange.

**Comment by bazilio91** [comment]
Create a PR and github will show you as a contributor.

**Comment by scriptjs** [comment]
@bazillo91 I am not using your package which is the reason I did not bother. I wrote one in es6 but wanted to pass on some information that might help you or others. If you use the information, then provide credit is all I ask

**Comment by vhtml** [comment]
don't support the syntax 'include'?

**Comment by AndreiSoroka** [comment]
@vhtml 
supported. But changes in "include files" webpack not auto compiled ({watch: true}) 
need run task again :(

**Comment by k-funk** [comment]
Could really use some notes in the readme about the es6 issues that the OP mentioned.

**Comment by scottbedard** [comment]
Alternatively, you can tell babel to ignore certain file extensions

```js
{
    test: /\.js|\.es6/,
    loader: 'babel-loader',
    options: {
        presets: ['es2015', 'stage-2'],
        ignore: ['*.jst']
    },
},
```

**Comment by bazilio91** [comment]
Anybody wants to become a contributor/collaborator? I have no interest to support this package now (I'm on DevOps title right now). I can't track all the changes that came in webpack.v2/es6.

**Comment by neginbasiri** [comment]
Hi all, I installed version 2 and my webpack 2 config is 
`module: { rules: [ { test: /\.ejs$/, use: [ 'ejs-compiled-loader' ] }]}`

I'm getting Module build failed: Error: Could not find include include file.

Do you know how to get it working? Do we need to pass any option to webpack config? can you please post your webpack config code?

**Comment by neginbasiri** [comment]
I get it working by changing path to relative and also using <%- require('component/component.ejs') ({data: data}) %> 
However webpack doesn't rebuilt on ejs files changes. Anyone knows hot to fix this?

**Comment by neginbasiri** [comment]
@AndreiSoroka Do you know how to get webpack watch changes for include files?

**Comment by bazilio91** [comment]
kinda rotten, reopen if needed.
