### ISSUE TITLE
Partials not found

### ISSUE THREAD

**Issue by mokargas** [bazilio91/ejs-compiled-loader#23]
No matter what I do to include partials, I always receive the following error "Error: ENOENT: no such file or directory". The EJS include does not resolve the partial, even if I move the partials to the same level as the 'entry' ejs file. I'm running with webpack-dev-server.

**What I'm trying to do:**

I have existing EJS files, I want to compile them (and their partials), then have the project accessible from dist/index.html (using html-webpack-plugin, see below). Previously this was a gulp task.

**Project structure:**
app/
- layouts/default.ejs
- main.ejs
- webpack.config.js

scripts/
- main.js

assets/
dist/

**In main.ejs, I have:**

`<%- include layouts/default -%>` 

**Relevant parts of webpack.config looks like:**
```
const appDir  = path.resolve(__dirname, 'app'),
      distDir = path.resolve(__dirname, 'dist')

---

  output: {
    devtoolLineToLine : true,
    sourceMapFilename : 'main.js.map',
    pathinfo          : true,
    path              : distDir,
    filename          : 'main.js'
  },
  module : {
    loaders: [
      {
        test: /.ejs$/,
        loader: 'ejs-compiled'
      },
      //Run JS through babel-loader
      {
        test   : /.js$/,
        loader : 'babel-loader',
        include: appDir,
        exclude: /node_modules/,
        query  : {
          plugins: ['lodash'],
          presets: ['es2015'],
        }
      },
..
}
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
    new HtmlWebpackPlugin({
  title    : 'Puzzle Slider Proto',
  template : '!!ejs-compiled-loader!' + appDir + '/main.ejs'
})
  ]
```

I'm using ES6 with:
"ejs-compiled-loader": "^1.1.0",
"babel-loader": "^6.2.5",
"html-webpack-plugin": "^2.24.1",

**Comment by jefffortune** [comment]
I am having the same issue.

**Comment by marianocodes** [comment]
Did anyone find a solution or workaround?

**Comment by mister-good-deal** [comment]
Same issue here ...

My stack is

- webpack 2
- ejs
- ejs-compiled-loader (for webpack)
- es6 syntax javascript source files like `import`

And when I use `import ejsPage from '../ejs/pages/ejsPage.ejs';` in a js source file, the import works in execution but if the `ejsPage.ejs` source file containes some `<%- include('directory/otherEjsPage') %>`, webpack fails at compiling with `Module build failed: Error: ENOENT: no such file or directory, open '('directory/otherEjsPage').ejs'`.

Here is my webpack config:

```js
const webpack        = require('webpack'),
      path           = require('path'),
      vendorsFiles   = require('./package.json').dependencies,
      cordovaPlugins = require('./package.json').cordova.plugins,
      webpackIgnore  = require('./package.json').webpackIgnore;

module.exports = {
    "entry"  : {
        "main"  : path.resolve(__dirname, 'www/js/app.js'),
        "vendor": Object.keys(vendorsFiles).filter((item) => Object.keys(cordovaPlugins).indexOf(item) === -1 &&
                                                             webpackIgnore.indexOf(item) === -1)
    },
    "output" : {
        "filename"         : "[name].js",
        "path"             : path.resolve(__dirname, 'www/js'),
        "sourceMapFilename": "[name].js.map"
    },
    "module" : {
        "loaders": [
            {"test": /\.json$/, "loader": "json-loader"},
            {"test": /\.ejs$/, "loader": "ejs-compiled-loader"}
        ]
    },
    "resolve": {
        "alias"  : {
            "hammerjs"       : path.resolve(__dirname, 'node_modules/hammerjs/hammer'),
            // Special version forked to fix jQuery issue
            "materialize-css": path.resolve(__dirname, 'node_modules/materialize-css/dist/js/materialize')
        },
        "modules": [
            path.resolve(__dirname, "node_modules"),
            // Use in ejs-compiled-loader to resolve the include directives in ejs files => NOT WORKING
            path.resolve(__dirname, "www/ejs/pages")
        ],
        "plugins": [
            new webpack.optimize.CommonsChunkPlugin(
                {
                    "names": ["vendor", "manifest"]
                }
            ),
            // Use in ejs-compiled-loader to access lodash from template at runtime
            new webpack.ProvidePlugin({"_": "_"})
        ]
    },
    "target" : "node",
    "devtool": "source-map"
};
```

**Comment by mister-good-deal** [comment]
I found the solution, while the [ejs](http://ejs.co/) official doc says that the syntax for import is `<%- include('user/show'); %>` it is actually `<%- include user/show %>`, I found it [here](https://stackoverflow.com/a/43402005/5154366).

I replace my includes with this new simpler syntax and webpack now compiles fine.

Do not forget to include with the path relative to your webpack config file.

Also, if you want to compile your file with CLI (not in runtime), like I do with gulp and [gulp-ejs](https://github.com/rogeriopvl/gulp-ejs) plugin; you must prefix your includes with `/` (like root path) (ex: `<%- include /project_root/some_dir/user/show %>`) and then set in ejs option `{"root": __dirname}` in your gulp file where `__dirname` is the absolute path of your `project_root`.

**Comment by Adam-Meisen** [comment]
I'm not a contributor, but I've been doing some work to figure out what the deal is with this package.

In short, if you're using the version installed by default from npm, the correct docs are [here](https://github.com/tj/ejs). You can install the actual latest version, which uses [this version of ejs](https://github.com/mde/ejs) with `npm install ejs-compiled-loader@^2.2.0` or `yarn add ejs-compiled-loader@^2.2.0`.

**Comment by Briggybros** [comment]
@Adam-Meisen That change gets rid of the old error and now throws 'esc is not a function'

**Comment by Adam-Meisen** [comment]
If you get the error `esc is not a function` after updating, that means that a variable in your partial is resolving to `undefined`. If you're doing something like this:
```
<% if (localVar) { %>
<%- localVar %>
<% } %>
```
try this:
```
<% let localVar = localVar || false; %>
<% if (localVar) { %>
<%- localVar %>
<% } %>
```

**Comment by janschloss** [comment]
@ZiperRom1 s answer worked for me. The path needs to be relative to the webpack config file.

**Comment by gregorskii** [comment]
I can't get this to work at all in my case.

Getting either:

```
Error: Could not find include include file.
```

Or:

```
Error: path is not defined
```

Of possible note is that my webpack config is in a subfolder, but the webpack command is run by `npm` a folder back.

This structure:

```
APP/package.json
APP/build/webpack.config.js
APP/src/entry.js
APP/src/templates/entry.ejs
```

Webpack config:

```
new HtmlWebpackPlugin({
    filename: `${entry}.html`,
    template: `./src/templates/${entry}.ejs`,
    inject: false,
    chunks: [entry]
  })
```

Depending on how I configure the includes.

Template:

```
<!DOCTYPE html>
<html lang="en">
<%- include @/templates/partials/head %>
<body class="home"> 

  // SOME HTML

  <% htmlWebpackPlugin.files.js.forEach(function(jsFile) { %>
    <script type="text/javascript" src="<%= jsFile %>"></script>
  <% }); %>
</body>

</html>
```

Partial:

```
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <% htmlWebpackPlugin.files.css.forEach(function(cssFile) { %>
      <link rel="stylesheet" href="<%= cssFile %>">
  <% }); %>
</head>
```

Does EJS have an argument for the base template path like nunjucks does? Can't a config for this plugin simply set an absolute path to hunt for includes?

It also appears that the plugin is not allowing webpack aliases to be evaluated, that's another way to solve it. One could simply create an alias for their templates folder.

I am trying to use this plugin with `html-webpack-plugin` to migrate a build another dev did with Gulp to webpack. Each entrypoint in my config has an associated ejs file with partials. I am trying to configure the compiler to work with `html-webpack-plugin` as to inject the `chunks` from webpack pertaining to the specific entry into an existing ejs page template.

**Comment by gregorskii** [comment]
Right after posting this... tried it without any pathing on the templates, and with version 2.0.0 it works.

Using this works:

```
"ejs-compiled-loader": "^2.2.0",
```

```
<!DOCTYPE html>
<html lang="en">
<%- include partials/head %>
<body class="home"> 

  // SOME HTML

  <% htmlWebpackPlugin.files.js.forEach(function(jsFile) { %>
    <script type="text/javascript" src="<%= jsFile %>"></script>
  <% }); %>
</body>

</html>
```

I think the confusion about NPM serving version 1 needs to be cleared up. From then on its just a matter of configuring it how EJS recommends: https://github.com/tj/ejs#includes
