### ISSUE TITLE
Checking optional parameter with ternary expression

### ISSUE THREAD

**Issue by jokarl** [bazilio91/ejs-compiled-loader#29]
Hi,

To check if a parameter is optional or not, this is the only way I've gotten it to work.

`<%= typeof optional!='undefined' ? optional : '' %>`

Shouldn't this work as well?

`<%= optional ? optional : '' %>`

Is there any other way to do this?

**Comment by jokarl** [comment]
An example for if ... else and a ternary expression would be appreciated. Having trouble to get any of them to work.

        <% if(optional) {
        include partial 
        } %>

partial.ejs:

	<h2><%= optional %></h2>

Results in this:

> Module build failed: SyntaxError: Unexpected identifier in "."
    at Object.exports.compile (C:\git\misc\designsystem\node_modules\ejs-compiled-loader\node_modules\ejs\lib\ejs.js:258:14)
    at Object.module.exports (C:\git\misc\designsystem\node_modules\ejs-compiled-loader\index.js:7:22)

It doesn't matter if supply the parameter `optional` or not, it still fails.

Just this:

	<%  include partial %>	

And passing the parameter `optional` works.  
If not passing `optional`, it compiles and I get an error in the console, which I expected to see.
> optional is not defined

**Comment by Adam-Meisen** [comment]
```
<% if(optional) {
include partial 
} %>
```
should look like
```
<% if(optional) { %>
<%- include partial %>
<% } %>
```

If you're using the version installed by default from npm, the correct docs are [here](https://github.com/tj/ejs). You can install the actual latest version, which uses [this version of ejs](https://github.com/mde/ejs) with `npm install ejs-compiled-loader@^2.2.0` or `yarn add ejs-compiled-loader@^2.2.0`

It's pretty confusing at the moment, took me a while to figure out.

Edit: Sorry, I forgot to answer the original question. I don't know if there's any way to keep it from spitting out an error when ejs tries to resolve `optional`. You might want to do something like 
```
<% var optional = optional || false; %>
<% if(optional) { %>
<%- include partial %>
<% } %>
```

**Comment by jokarl** [comment]
Thank you! I upgraded to 2.2.0 and it also allows include paths to be relative to the template. Had some problems in mocha when they were relative to where webpack was run.
