### ISSUE TITLE
ejs 2.x?

### ISSUE THREAD

**Issue by IngwiePhoenix** [bazilio91/ejs-compiled-loader#3]
I just installed this loader...and saw this in the output.

```
ejs@2.3.1 node_modules/ejs

ejs-compiled-loader@0.2.0 node_modules/ejs-compiled-loader
├── ejs@1.0.0
└── uglify-js@1.3.5
```

Why aren't you using the newer version?

**Comment by bazilio91** [comment]
mde/ejs repo is fresh and was created after this plugin. Latest tj/ejs is release is still 1.0.0 https://github.com/tj/ejs/releases. I'm sure I can support both versions in 2.x.x and 1.x.x branches of this plugin if it's needed.

**Comment by IngwiePhoenix** [comment]
Oh jeez. So both versions are maintained by different developers? What a confusion this is...
What is the difference between the both?

**Comment by bazilio91** [comment]
I didnt used 2.x version, but there is note about removal of filters in 2.x readme. You can fork and try to switch, if it works - I will create 2.x branch from your fork

**Comment by IngwiePhoenix** [comment]
Going to give it a shot. :)

**Comment by IngwiePhoenix** [comment]
https://github.com/IngwiePhoenix/ejs-compiled-loader/commit/e341aec5511a66a67bf9b8b9f0915c85347a5cf9

Added a teeny tiny webpack test, hence the added devDependency.

I have only tested basic usage here, but from what other tests - that i did not upload - I do, I saw no problems whatsoever.

**Comment by IngwiePhoenix** [comment]
BTW, why are you creating an AST and asking uglify to parse the AST? Any specific reason? I am just asking because I was reading the code, looking if I could change % to ? using the delimiter option.

I'd suggest you to check out http://npmjs.org/loader-utils . You can get parameters from the user and add it to the `.compile()` call. Just an idea, though.

**Comment by bazilio91** [comment]
It is used to include ejs functions to template (we don't have any ejs code on clientside anywhere else). Only that.

**Comment by IngwiePhoenix** [comment]
Oh, I see! Only time that I really went close to an actual AST was, when I was working with a compiles-to-javascript system like Coffee or OJ. :)

**Comment by bazilio91** [comment]
Branches are set, npm packages are ok.

**Comment by bazilio91** [comment]
NPM index is a bit slowpoke, so packages will appear later.

**Comment by IngwiePhoenix** [comment]
Haha, thats okay. Glad I could help on this one! Hope you'll allow user options soon (via the query string, that is)

**Comment by bazilio91** [comment]
Send me an issue :) I'll be back on this repo in 2-3 months.

**Comment by IngwiePhoenix** [comment]
2-3 months?... Okay, I think in that time I might implemented it on my own. Going to make that a PR, then. :)
