### ISSUE TITLE
Drop-In-Replacement for this

### ISSUE THREAD

**Issue by yetzt** [bazilio91/ejs-compiled-loader#44]
Since this package collects dust and vulnerable dependencies, i've made an up-to-date drop-in-replacement:

https://www.npmjs.com/package/ejs-loader-compiled

You're welcome.

**Comment by bazilio91** [comment]
I have some time now for this. Will you accept full rights (maybe with transfer into some organisation) on this repo and maintain this?

**Comment by yetzt** [comment]
i can agree to keep it up to date and take care of updating dependencies if vulnerabilities should occur, but nothing beyond that. maybe also aks the folks from #25

**Comment by bazilio91** [comment]
any help is much appreciated

**Comment by bazilio91** [comment]
#25 folks are asked

**Comment by bazilio91** [comment]
plz check ur mail for maintainer invite.

**Comment by yetzt** [comment]
got it. im'm also [yetzt](https://www.npmjs.com/~yetzt) on npm
