### ISSUE TITLE
Allow includes relative to file location

### ISSUE THREAD

**Issue by taion** [bazilio91/ejs-compiled-loader#6]
Would it be possible to enable this as a config setting? Currently this loader cannot produce the same behavior as `transform?ejsify` when includes are involved, and I'd like to be able to use this loader instead of `transform?ejsify`.

**Comment by bazilio91** [comment]
Which version are you using? It is possible with ejs 2 as said in docs https://github.com/mde/ejs#includes

**Comment by taion** [comment]
It should. The problem is that `this.context` in a webpack loader doesn't return the project root, but instead the directory in which the processed file is located: https://webpack.github.io/docs/loaders.html#context.

This means that https://github.com/bazilio91/ejs-compiled-loader/blob/2.0.2/index.js#L19 just returns the file's basename. I think instead you need maybe `process.cwd()` instead of `this.context`.

**Comment by bazilio91** [comment]
Ok, can u submit a test so I can clearly understand this case?

**Comment by taion** [comment]
I added a test fixture in #7 that demonstrates the issue.

**Comment by taion** [comment]
Thanks! Would you mind releasing this? It's blocking me from switching over from ejsify via transform.
